### ISSUE TITLE
Error while using Sequel gem

### ISSUE THREAD

**Issue by arni1981** [jsonapi-serializer/jsonapi-serializer#112]
I'm having trouble getting this to work with the Sequel gem, no problems when using Rails ActiveRecord.

## Expected Behavior
```
class UserSequel < Sequel::Model(:users)
end

class UserSerializer
  include FastJsonapi::ObjectSerializer
  attributes :text
end

UserSerializer.new(UserSequel.first).serializable_hash.to_json
```
I expect this to output the desired JSON

## Actual Behavior
However, what happens is this error, which is strange because this obviously has a column `id`

**_FastJsonapi::MandatoryField (id is a mandatory field in the jsonapi spec)_**

## Steps to Reproduce the Problem

  1. Create a Rails api project with `rails new sandbox --api`
  2. `gem 'sequel'` `gem 'sequel-rails'`
  3. Generate a serializer for user

## Specifications

  - Version: 2.0.0
  - Ruby version: 2.7.1

[I asked about this on Stackoverflow also](https://stackoverflow.com/questions/63403607/using-sequel-with-jsonapi-serializer)

**Comment by stas** [comment]
Thanks @arni1981!

Might be the time to actually add a test or two for sequel :see_no_evil:

**Comment by stas** [comment]
@arni1981 I'm not a Sequel expert, but looking at their documentation, Sequel is referring to the `pk` as the primary key method. So the right way would be first to tell the serializer to use `set_id :pk`.


Aside from this, for some reason Sequel::Model instance responds to `:each` by iterating through the model instance attributes, and for that reason, it tries to serialize the instance attributes and not the model itself. This is weird, but I'd say it's our fault since we really should stick to only `Enumerable` inherited objects as collections:
https://github.com/jsonapi-serializer/jsonapi-serializer/blob/master/lib/fast_jsonapi/object_serializer.rb#L108-L112

If anybody else has different suggests how to tackle this, I'll be happy to take a look. Otherwise, I think fixing the `is_collection?` should fix it all for everyone... :see_no_evil:

**Comment by arni1981** [comment]
Using `set_id :pk` works if you're working with a Sequel dataset like `User.where(id: [1,2])`, not if you're working with a single instance `User.first(id: 1)`, then the error message is **undefined method `pk' for [:id, 1]:Array**
