### ISSUE TITLE
Moving from fast_jsonapi to jsonapi-serializer - anything to worry about?

### ISSUE THREAD

**Issue by tonydehnke** [jsonapi-serializer/jsonapi-serializer#120]
First time dealing with a gem/repo name change.

Is there anything we need to do or worry about when replacing the old fast-jsonapi gem in our project with jsonapi-serializer?

Any advice or heads-up on things would be great.

Thank you.

**Comment by stas** [comment]
@tonydehnke there should be no major changes required to make the switch. In fact, you can still do things like `require 'fast_jsonapi'` since we tried to keep v2 compatible with what was before `fast_jsonapi`. Some changes did happen though, please review the `CHANGELOG.md` for those, but everything should be documented in the readme.

Let us know if you discover anything....

**Comment by stas** [comment]
@tonydehnke I'm closing this in favor of #139
