### ISSUE TITLE
How to serialize custom, non ActiveRecord, relationship?

### ISSUE THREAD

**Issue by heldersantosmoreira** [jsonapi-serializer/jsonapi-serializer#122]
Any suggestions on how to be able to serialize a custom relationship that is not an ActiveRecord one?

Doing

`belongs_to :foo`

seems to assume and expect that `foo` will be an ActiveRecord relationship (it will try to look it up using `foo_id` for instance).

Let's assume I have a PORO "relationship" in my object called `xxx`.

```ruby
class Foo
  include ActiveModel::Model

  attr_accessor :id, :type
end

class Bar < ApplicationRecord
  def foo
    Foo.new(...)
  end
end
```

How could I serialize this and make it go into the relationships instead of the attributes?

**Comment by stas** [comment]
@heldersantosmoreira the tests we have a not using ActiveRecord, so that could be a good starting point where to explore:
https://github.com/jsonapi-serializer/jsonapi-serializer/blob/master/spec/fixtures/movie.rb

As for your specific question, take a look at the [options you can pass](https://github.com/jsonapi-serializer/jsonapi-serializer#customizable-options) to help modify the way the relationship IDs are fetched.

Let me know if that helps.

**Comment by heldersantosmoreira** [comment]
Thank you for the quick and helpful response @stas 🙏 

I had a look at those options but hadn't quite managed to get it going. Having a look at the specs unblocked it for me 👍
