### ISSUE TITLE
Namespaced Models

### ISSUE THREAD

**Issue by 2009** [jsonapi-serializer/jsonapi-serializer#151]
I'm migrating from `fast_jsonapi` and before relationships with a namespaced model would resolve to a serializer that included the namespace, but now they get ignored.

Given the following serializer:

```ruby
class Serializers::OrderSerializer
  has_many :items, polymorphic: true
end
```

If an item had a class `Order::Book` it would resolve to `Serializers::Order::BookSerializer`, but now it resolves to just `Serializers::BookSerializer`.

Was this an intended change? I would expect the previous behaviour, if I also had un-namespaced `Book` class and serializer I would be forced to manually handle resolving all serializers for `items`.

**Comment by stas** [comment]
@2009 it is intended and the relevant change was introduced in #32 

The reason this change was introduced is because of the inconsistencies between how a relationship serializer would get resolved (your example) and how any other serializer would get resolved (example, relationship name derived serializer). Basically there were two implementations with the same purpose that would yield different results. We moved it all into one API method and unfortunately, implementations like yours, would break.

The best way to move forward with this is to either provide a proc where you have your own serializer resolved based on the _item_ class, or provide a hash with record types/serializer classes on the polymorphic relationship.

I'd suggest to move forward with the first one, since your scenario is uncommon, this way there should be no breaking changes. Plus the API support on relationships for `serializer: -> {|object| ....}` are here to stay since it provides the most flexibility for everyone.

There's more work being completed in #141 where we won't longer rely on the _magical ways_ to resolve serializers and instead will be registering available serializers and lookup exclusively within those:
https://github.com/jsonapi-serializer/jsonapi-serializer/pull/141/files#diff-730e95e3efab398dfa4d5e74ae11d9728a7a771b7322c22f3fb489fd70f77234R6

**Comment by 2009** [comment]
Thanks @stas, that makes sense I'll do what you suggest. I also came across some of the inconsistency previously.

I'll look forward to the v3 release. 😄
