### ISSUE TITLE
URL Helpers?

### ISSUE THREAD

**Issue by aximuseng** [jsonapi-serializer/jsonapi-serializer#157]
Is it possible to access the url helpers?

I tried:

```
  include ActionController::Helpers
  include ActionView::Helpers
  include ActionDispatch::Routing::UrlFor
```
I am trying to do something like this:

```
  link :self do |object|
    api_v1_movies_url(object)
  end
```

where `api_v1_movies_url` is an example named route I have for my API that this run under.

I get these errors:  `undefined method 'api_v1_movies_url' for MovieSerializer:Class`

There are other issues that seem to indicate you can do this - wondering if I am missing something minor here.  I really don't want to build all these URLs manually for each model etc.

**Comment by doits** [comment]
You can include [Rails.application.routes.url_helpers](https://api.rubyonrails.org/v6.0.0/classes/ActionDispatch/Routing/UrlFor.html#module-ActionDispatch::Routing::UrlFor-label-URL+generation+for+named+routes). Since everything is evaluated on class level, you must include it into the class or singleton class:

```ruby
class MoviesSerializer
  singleton_class.include Rails.application.routes.url_helpers
end
```

**Comment by aximuseng** [comment]
That did the trick - thanks.

**Comment by azorrillav** [comment]
This works as well
```ruby
class MoviesSerializer
  class << self
    include Rails.application.routes.url_helpers
  end
end
```
